### ISSUE TITLE
Lower borders of tab list headers behaving invorrectly on mobile layout

### ISSUE THREAD

**Issue by MiniDigger** [PaperMC/papermc.io#7]
https://irc.minidigger.me/uploads/76675946508b51ca/25-10-2018%2009-20-21.mp4 
both firefox on desktop with small window and chrome on mobile are affected.

**Comment by MiniDigger** [comment]
disabling this in line 20 of download.css partly fixes it
```css
  #downloads-tabs {
    height: auto;
    /*! position: initial; */
    display: block;
  }
```
now the border is always displayed on the lower two of the four tabs. better than before, still not good, but I honestly don't even know how it should look in a square layout, especially with the sliding animation
